services:
  - type: static
    name: CineVibe
    env: static
    buildCommand: npm run build
    publishDir: dist
    staticPublishPath: dist
    headers:
      - source: /*
        headers:
          - key: Cache-Control
            value: no-cache
    redirects:
      - source: /*
        destination: /index.html
        status: 200
